### ISSUE TITLE
Customize Long Press Menu

### ISSUE THREAD

**Issue by toshi0383** [noppefoxwolf/DebugMenu#17]
Motivation is that we'd like to localize these messages.
<img width="361" alt="スクリーンショット 2021-10-12 19 26 07" src="https://user-images.githubusercontent.com/6007952/136939131-eac74216-6b6e-48d1-b4d8-cf9f6a6c2e88.png">

Thoughts?

**Comment by noppefoxwolf** [comment]
Thank you for your feedback.

Now available support localization.
https://github.com/noppefoxwolf/DebugMenu/releases/tag/2.0.3
